-- MySQL Script generated by MySQL Workbench
-- Вт 27 окт 2020 16:24:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ORGANIZATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ORGANIZATION` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ORGANIZATION` (
  `ID_ORGANIZATION` INT NOT NULL,
  `INN` INT NOT NULL,
  `CHECKING_ACCOUNT` INT NOT NULL,
  PRIMARY KEY (`ID_ORGANIZATION`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`WAYBILL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`WAYBILL` ;

CREATE TABLE IF NOT EXISTS `mydb`.`WAYBILL` (
  `ID_WAYBILL` INT NOT NULL AUTO_INCREMENT,
  `DATE` DATE NOT NULL,
  `ID_ORGANIZATION` INT NOT NULL,
  PRIMARY KEY (`ID_WAYBILL`),
  INDEX `fk_WAYBILL_1_idx` (`ID_ORGANIZATION` ASC) ,
  CONSTRAINT `fk_WAYBILL_1`
    FOREIGN KEY (`ID_ORGANIZATION`)
    REFERENCES `mydb`.`ORGANIZATION` (`ID_ORGANIZATION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NOMENCLATURE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`NOMENCLATURE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`NOMENCLATURE` (
  `ID_NOMENCLATURE` INT NOT NULL,
  `NAME` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_NOMENCLATURE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`POSITION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`POSITION` ;

CREATE TABLE IF NOT EXISTS `mydb`.`POSITION` (
  `ID_POSITION` INT NOT NULL AUTO_INCREMENT,
  `ID_WAYBILL` INT NOT NULL,
  `ID_NOMENCLATURE` INT NOT NULL,
  `COST` DOUBLE NOT NULL,
  `COUNT` INT NOT NULL,
  INDEX `fk_POSITION_1_idx` (`ID_WAYBILL` ASC),
  INDEX `fk_POSITION_2_idx` (`ID_NOMENCLATURE` ASC) ,
  PRIMARY KEY (`ID_POSITION`),
  CONSTRAINT `fk_POSITION_1`
    FOREIGN KEY (`ID_WAYBILL`)
    REFERENCES `mydb`.`WAYBILL` (`ID_WAYBILL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_POSITION_2`
    FOREIGN KEY (`ID_NOMENCLATURE`)
    REFERENCES `mydb`.`NOMENCLATURE` (`ID_NOMENCLATURE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;