-- MySQL Script generated by MySQL Workbench
-- Вс 25 окт 2020 14:35:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`LECTURER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LECTURER` ;

CREATE TABLE IF NOT EXISTS `mydb`.`LECTURER` (
  `ID_LECTURE` INT NOT NULL AUTO_INCREMENT,
  `NAME_LECTURE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_LECTURE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`STUDENTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`STUDENTS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`STUDENTS` (
  `ID_STUDENT` INT NOT NULL AUTO_INCREMENT,
  `NAME_STUDENT` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_STUDENT`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COURSE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`COURSE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`COURSE` (
  `ID_COURSE` INT NOT NULL AUTO_INCREMENT,
  `NAME_COURSE` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_COURSE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ENROLLED_STUDENTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ENROLLED_STUDENTS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ENROLLED_STUDENTS` (
  `ID_ENROLLED_STUDENT` INT NOT NULL AUTO_INCREMENT,
  `ID_STUDENT` INT NOT NULL,
  `ID_COURSE` INT NOT NULL,
  PRIMARY KEY (`ID_ENROLLED_STUDENT`),
  INDEX `fk_ENROLLED_STUDENTS_1_idx` (`ID_STUDENT` ASC),
  INDEX `fk_ENROLLED_STUDENTS_2_idx` (`ID_COURSE` ASC),
  CONSTRAINT `fk_ENROLLED_STUDENTS_1`
    FOREIGN KEY (`ID_STUDENT`)
    REFERENCES `mydb`.`STUDENTS` (`ID_STUDENT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ENROLLED_STUDENTS_2`
    FOREIGN KEY (`ID_COURSE`)
    REFERENCES `mydb`.`COURSE` (`ID_COURSE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LESSON`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LESSON` ;

CREATE TABLE IF NOT EXISTS `mydb`.`LESSON` (
  `ID_LESSON` INT NOT NULL,
  `DATE` DATE NOT NULL,
  `ID_LECTURER` INT NOT NULL,
  `ID_COURSE` INT NULL,
  PRIMARY KEY (`ID_LESSON`),
  INDEX `fk_LESSON_1_idx` (`ID_LECTURER` ASC) ,
  INDEX `fk_LESSON_2_idx` (`ID_COURSE` ASC),
  CONSTRAINT `fk_LESSON_1`
    FOREIGN KEY (`ID_LECTURER`)
    REFERENCES `mydb`.`LECTURER` (`ID_LECTURE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LESSON_2`
    FOREIGN KEY (`ID_COURSE`)
    REFERENCES `mydb`.`COURSE` (`ID_COURSE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`STUDENT_PROGRESS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`STUDENT_PROGRESS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`STUDENT_PROGRESS` (
  `ID_LESSON` INT NOT NULL,
  `ID_STUDENT` INT NOT NULL,
  `HOMEWORK` INT NULL,
  `LECTURES` TINYINT NULL,
  INDEX `fk_STUDENT_PROGRESS_1_idx` (`ID_STUDENT` ASC) ,
  INDEX `fk_STUDENT_PROGRESS_2_idx` (`ID_LESSON` ASC) ,
  CONSTRAINT `fk_STUDENT_PROGRESS_1`
    FOREIGN KEY (`ID_STUDENT`)
    REFERENCES `mydb`.`ENROLLED_STUDENTS` (`ID_ENROLLED_STUDENT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_STUDENT_PROGRESS_2`
    FOREIGN KEY (`ID_LESSON`)
    REFERENCES `mydb`.`LESSON` (`ID_LESSON`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

USE `mydb`;
DROP  IF EXISTS `mydb`.`routine1`;

DELIMITER $$
USE `mydb`$$
$$

DELIMITER ;

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
DROP VIEW IF EXISTS `mydb`.`view1` ;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;